const stages=[
  {location:'GRANUM',type:'IŞIĞIN KULLANILDIĞI',title:'Işık yakalanır.',text:'Klorofil ve yardımcı pigmentler ışığı soğurur. Klorofilin elektronları uyarılır ve elektron taşıma sistemine aktarılır.',takeaway:'Başlangıç noktası: güneşten gelen ışık enerjisi.',zones:['light','thylakoid']},
  {location:'GRANUM',type:'IŞIĞIN KULLANILDIĞI',title:'Su parçalanır.',text:'Işık enerjisiyle su fotolize uğrar; elektronlar, H⁺ iyonları ve oksijen oluşur. Sudan gelen elektronlar klorofilin kaybettiği elektronların yerini alır.',takeaway:'Oksijenin kaynağı sudur: H₂O → e⁻ + H⁺ + O₂.',zones:['thylakoid']},
  {location:'GRANUM',type:'IŞIĞIN KULLANILDIĞI',title:'Elektronlar yola çıkar.',text:'Elektronlar, elektron taşıma sistemi (ETS) boyunca ilerlerken açığa çıkan enerjinin bir kısmı ATP sentezinde kullanılır.',takeaway:'Kitaptaki modelde ETS, ATP sentezinin ana basamaklarından biridir.',zones:['thylakoid','energy']},
  {location:'GRANUM → STROMA',type:'IŞIĞIN KULLANILDIĞI',title:'ATP ve NADPH üretilir.',text:'NADP⁺, fotolizle sağlanan elektronları ve H⁺ iyonlarını alarak NADPH’ye dönüşür. Oluşan ATP ve NADPH, ikinci evrede organik madde üretimi için kullanılır.',takeaway:'ATP ve NADPH, Calvin döngüsüne aktarılır.',zones:['thylakoid','energy']},
  {location:'STROMA',type:'IŞIĞIN KULLANILMADIĞI',title:'Karbon organik maddeye katılır.',text:'Calvin döngüsünde CO₂, ATP ve NADPH kullanılarak üç karbonlu PGAL oluşur. PGAL’den glikoz ve başka organik bileşikler sentezlenebilir.',takeaway:'CO₂ → PGAL → organik bileşikler.',zones:['energy','calvin']}
];
let currentStage=0;
const $=(selector)=>document.querySelector(selector);
function renderStage(index){currentStage=Math.max(0,Math.min(index,stages.length-1));const s=stages[currentStage];$('#stage-current').textContent=String(currentStage+1).padStart(2,'0');$('#stage-location').textContent=s.location;$('#stage-type').textContent=s.type;$('#stage-title').textContent=s.title;$('#stage-text').textContent=s.text;$('#stage-takeaway').lastElementChild.textContent=s.takeaway;$('#model-view').dataset.stage=String(currentStage);document.querySelectorAll('.model-zone').forEach(el=>el.classList.toggle('is-lit',s.zones.some(zone=>el.classList.contains('zone-'+zone))));document.querySelectorAll('.stage-button').forEach((button,i)=>{const selected=i===currentStage;button.classList.toggle('active',selected);button.setAttribute('aria-pressed',String(selected))});$('#prev-stage').disabled=currentStage===0;$('#next-stage').disabled=currentStage===stages.length-1}
document.querySelectorAll('.stage-button').forEach(button=>button.addEventListener('click',()=>renderStage(Number(button.dataset.stage))));$('#prev-stage').addEventListener('click',()=>renderStage(currentStage-1));$('#next-stage').addEventListener('click',()=>renderStage(currentStage+1));renderStage(0);

const parts={outer:{number:'01',title:'Dış zar',description:'Kloroplastı dıştan çevreler ve organeli hücrenin sitoplazmasından ayırır.'},inner:{number:'02',title:'İç zar',description:'Çift katmanlı zarın içteki kısmıdır. Stromayı çevreleyerek organelin iç ortamının düzenlenmesine katkı verir.'},thylakoid:{number:'03',title:'Tilakoit',description:'Kloroplast içindeki yassı zar keseciğidir. Klorofil ve yardımcı pigmentler tilakoit zarında bulunur.'},granum:{number:'04',title:'Granum',description:'Üst üste dizilmiş tilakoitlerin oluşturduğu yığındır. Ders kitabı, ışığın kullanıldığı tepkimelerin granumda gerçekleştiğini söyler.'},stroma:{number:'05',title:'Stroma',description:'Tilakoitlerin çevresindeki sıvı bölgedir. Işığın kullanılmadığı tepkimeler, yani Calvin döngüsü burada gerçekleşir.'}};
function renderPart(key){const p=parts[key];if(!p)return;$('#part-number').textContent=`YAPI ${p.number} / 05`;$('#part-title').textContent=p.title;$('#part-description').textContent=p.description;document.querySelectorAll('[data-part]').forEach(button=>{const selected=button.dataset.part===key;button.classList.toggle('active',selected);button.classList.toggle('selected',selected);if(button.classList.contains('hotspot'))button.setAttribute('aria-pressed',String(selected))})}document.querySelectorAll('[data-part]').forEach(button=>button.addEventListener('click',()=>renderPart(button.dataset.part)));

const questions=[
  {question:'Fotosentezde açığa çıkan oksijenin kaynağı hangisidir?',options:['Karbondioksit','Su','PGAL','Klorofil'],correct:1,explanation:'Işığın kullanıldığı tepkimelerde su fotolizle parçalanır; açığa çıkan oksijen sudan gelir.'},
  {question:'Calvin döngüsü kloroplastın hangi kısmında gerçekleşir?',options:['Stroma','Granum','Dış zar','Tilakoit zarı'],correct:0,explanation:'Calvin döngüsü stromada, ışığın kullanıldığı tepkimeler ise granumda gerçekleşir.'},
  {question:'Fotosentetik pigmentler kloroplastta nerede yer alır?',options:['Dış zarda','Stromada serbest hâlde','Tilakoit zarında','Çekirdekte'],correct:2,explanation:'Pigmentler granumu oluşturan tilakoitlerin zarlarında yer alır.'},
  {question:'Işığın kullanıldığı tepkimeler Calvin döngüsüne hangi iki molekülü sağlar?',options:['O₂ ve CO₂','Su ve glikoz','ATP ve NADPH','ADP ve NADP⁺'],correct:2,explanation:'Calvin döngüsü ATP ve NADPH kullanarak CO₂’den PGAL sentezler.'}
];let quizIndex=0,score=0,answered=false;
function renderQuiz(){answered=false;const q=questions[quizIndex];$('#quiz-question').textContent=q.question;$('#quiz-progress-text').textContent=`SORU ${String(quizIndex+1).padStart(2,'0')} / 04`;$('#quiz-progress-fill').style.width=`${(quizIndex+1)/questions.length*100}%`;$('#quiz-score').textContent=`${score} / 4 DOĞRU`;$('#quiz-feedback').hidden=true;$('#quiz-next').hidden=true;const container=$('#quiz-options');container.replaceChildren();q.options.forEach((option,i)=>{const button=document.createElement('button');button.className='quiz-option';button.textContent=option;button.addEventListener('click',()=>answerQuiz(i));container.append(button)})}
function answerQuiz(choice){if(answered)return;answered=true;const q=questions[quizIndex];if(choice===q.correct)score++;[...$('#quiz-options').children].forEach((button,i)=>{button.disabled=true;if(i===q.correct)button.classList.add('correct');else if(i===choice)button.classList.add('incorrect')});$('#quiz-score').textContent=`${score} / 4 DOĞRU`;$('#quiz-feedback').hidden=false;$('#quiz-feedback').textContent=`${choice===q.correct?'Doğru!':'Bu kez olmadı.'} ${q.explanation}`;$('#quiz-next').hidden=false;$('#quiz-next').innerHTML=quizIndex===questions.length-1?'Yeniden dene <span aria-hidden="true">↻</span>':'Sonraki soru <span aria-hidden="true">→</span>'}
$('#quiz-next').addEventListener('click',()=>{if(quizIndex===questions.length-1){quizIndex=0;score=0}else quizIndex++;renderQuiz()});renderQuiz();

const molecules={
  pigments:{label:'01 / IŞIK HASADI',title:'Önce enerji aktarılır.',text:'Klorofil a, klorofil b ve karotenoidler farklı dalga boylarındaki ışığı soğurur. Anten pigmentleri enerjiyi fotosistemin tepkime merkezine iletir. Elektronun ayrılması tepkime merkezinde gerçekleşir.',insight:'Enerji pigmentler arasında aktarılır; elektronun ETS’ye geçişi daha sonraki adımdır.',source:'OpenStax Biology 2e',url:'https://openstax.org/books/biology-2e/pages/8-2-the-light-dependent-reactions-of-photosynthesis'},
  psii:{label:'02 / FOTOSİSTEM II',title:'Suyun elektronları devreye girer.',text:'Fotosistem II’nin kaybettiği elektronlar sudan tamamlanır. Su parçalanırken oksijen ve H⁺ oluşur. Protein kompleksindeki manganez-kalsiyum merkezi, bu su yükseltgenmesini mümkün kılar.',insight:'İki H₂O’dan bir O₂, dört elektron ve dört H⁺ oluşur. “II” sayısı işlem sırasını göstermez.',source:'Li ve ark., Nature (2024)',url:'https://www.nature.com/articles/s41586-023-06987-5'},
  etc:{label:'03 / ELEKTRON TAŞIMA SİSTEMİ',title:'Elektronların yolu proton farkı kurar.',text:'Elektronlar plastokinon, sitokrom b₆f kompleksi ve plastosiyanin gibi taşıyıcılar üzerinden Fotosistem I’e ilerler. Bu aktarım, H⁺ iyonlarının tilakoit boşluğunda birikmesine katkı sağlar.',insight:'Tilakoit boşluğuna “lümen”, onu çevreleyen sıvı bölgeye “stroma” denir.',source:'OpenStax Biology 2e',url:'https://openstax.org/books/biology-2e/pages/8-2-the-light-dependent-reactions-of-photosynthesis'},
  psi:{label:'04 / FOTOSİSTEM I',title:'Işık elektrona yeniden enerji verir.',text:'Fotosistem I’de soğurulan ışık, elektronları tekrar yüksek enerjili hâle getirir. Son aşamada bu elektronlar NADP⁺’ın NADPH’ye indirgenmesine katılır.',insight:'NADPH, Calvin döngüsündeki karbon indirgenmesi için elektron sağlar.',source:'OpenStax Biology 2e',url:'https://openstax.org/books/biology-2e/pages/8-2-the-light-dependent-reactions-of-photosynthesis'},
  atp:{label:'05 / ATP SENTAZ',title:'Proton akışı ATP üretir.',text:'Tilakoit boşluğunda biriken H⁺ iyonları, ATP sentaz adlı proteinden stromaya geri geçer. Bu akışın enerjisi ADP ile inorganik fosfatın birleşerek ATP oluşturmasını sağlar.',insight:'Işığın enerjisi önce proton farkına, ardından kullanılabilir kimyasal enerjiye çevrilir.',source:'Michigan State University',url:'https://openbooks.lib.msu.edu/cellsandmolecules/chapter/photosynthesis/'},
  calvin:{label:'06 / CALVIN DÖNGÜSÜ',title:'CO₂ organik yapıya katılır.',text:'Stromada RuBisCO enzimi CO₂’yi RuBP adlı beş karbonlu moleküle bağlar. İndirgenme ve yenilenme basamakları sonunda net PGAL (G3P) döngüden ayrılır; kalanı RuBP’nin yeniden oluşmasına gider.',insight:'Bu döngüde ışık doğrudan kullanılmaz; ATP ve NADPH’ye bağımlılık sürer.',source:'Michigan State University',url:'https://openbooks.lib.msu.edu/cellsandmolecules/chapter/photosynthesis/'}
};
function renderMolecule(key){const item=molecules[key];if(!item)return;$('#molecule-label').textContent=item.label;$('#molecule-title').textContent=item.title;$('#molecule-text').textContent=item.text;$('#molecule-insight').textContent=item.insight;$('#molecule-source').href=item.url;$('#molecule-source').textContent=`Bu bilginin kaynağı: ${item.source} ↗`;document.querySelectorAll('.molecule-button').forEach(button=>{const active=button.dataset.molecule===key;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('.molecule-button').forEach(button=>button.addEventListener('click',()=>renderMolecule(button.dataset.molecule)));
function renderCarbon(co2){const multiple=co2/3;$('#carbon-atp').textContent=String(9*multiple);$('#carbon-nadph').textContent=String(6*multiple);$('#carbon-pgal').textContent=String(multiple);$('#carbon-note').textContent=multiple===1?'Üç tur sonucunda döngüden net bir PGAL ayrılır. Bu molekül şeker ve başka organik bileşiklerin yapımında kullanılabilir.':'Altı turda net iki PGAL oluşur. Bu iki üç karbonlu ürün, altı karbonlu şekerlerin yapımına katkı verebilir; glikoz tek adımda doğrudan üretilmez.';document.querySelectorAll('[data-co2]').forEach(button=>{const active=Number(button.dataset.co2)===co2;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('[data-co2]').forEach(button=>button.addEventListener('click',()=>renderCarbon(Number(button.dataset.co2))));
